#arquivos de migração do banco de dados, gerados pelo Alembic, para criar as tabelas iniciais do projeto.
"""cria_tabelas_iniciais

Revision ID: 373ad921086d
Revises: 001
Create Date: 2026-04-13 19:25:22.637338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '373ad921086d'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_categoria_imagens',
    sa.Column('categoria', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('categoria')
    )
    op.create_index(op.f('ix_pedidos_id_pedido'), 'pedidos', ['id_pedido'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pedidos_id_pedido'), table_name='pedidos')
    op.drop_table('dim_categoria_imagens')
    # ### end Alembic commands ###
